/* ==========================================================================
   Asset store.

   Rules from docs/architecture/data.md and docs/architecture/security.md:
     - paths are generated by the server, never derived from a prompt or a
       user-supplied filename
     - the browser receives a controlled resource URL, never a filesystem path
     - writes are atomic (temp file + rename) so a crash cannot leave a
       half-written asset that later looks valid
     - identity is the content hash, so re-importing the same result does not
       create a duplicate and does not require regenerating
     - deleting checks references and reports the impact instead of breaking
       a project that still uses the file
   ========================================================================== */

import {
  createHash,
  randomUUID,
} from "node:crypto";
import {
  createWriteStream,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  statSync,
  unlinkSync,
} from "node:fs";
import { join, resolve, extname } from "node:path";
import { pipeline } from "node:stream/promises";
import { openDb } from "./db.mjs";

const ASSET_SCHEMA = `
CREATE TABLE IF NOT EXISTS assets (
  id            TEXT PRIMARY KEY,
  content_hash  TEXT NOT NULL,
  byte_size     INTEGER NOT NULL,
  media_type    TEXT NOT NULL,
  storage_path  TEXT NOT NULL,
  display_name  TEXT NOT NULL,
  source_job_id TEXT,
  origin        TEXT NOT NULL,
  license_source TEXT,
  created_at    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS assets_by_hash ON assets(content_hash);
`;

/** Extensions we are willing to store and serve. */
const ALLOWED = new Map([
  [".mp3", "audio/mpeg"],
  [".wav", "audio/wav"],
  [".m4a", "audio/mp4"],
  [".ogg", "audio/ogg"],
  [".flac", "audio/flac"],
  [".mp4", "video/mp4"],
  [".webm", "video/webm"],
  [".png", "image/png"],
  [".jpg", "image/jpeg"],
  [".jpeg", "image/jpeg"],
  [".webp", "image/webp"],
  [".gif", "image/gif"],
  [".srt", "application/x-subrip"],
  [".vtt", "text/vtt"],
  [".txt", "text/plain; charset=utf-8"],
  [".json", "application/json; charset=utf-8"],
]);

/** Cap on a single import. Matches the "raw upload limit" requirement. */
export const MAX_ASSET_BYTES = 200 * 1024 * 1024;

export class StorageFullError extends Error {
  constructor(message) {
    super(message);
    this.code = "STORAGE_FULL";
  }
}

/** Content type -> extension, for naming a download with no filename. */
const EXT_BY_TYPE = new Map([
  ["audio/mpeg", ".mp3"],
  ["audio/wav", ".wav"],
  ["audio/mp4", ".m4a"],
  ["audio/ogg", ".ogg"],
  ["audio/flac", ".flac"],
  ["video/mp4", ".mp4"],
  ["video/webm", ".webm"],
  ["image/png", ".png"],
  ["image/jpeg", ".jpg"],
  ["image/webp", ".webp"],
  ["image/gif", ".gif"],
  ["application/x-subrip", ".srt"],
  ["text/vtt", ".vtt"],
  ["application/json", ".json"],
  ["text/plain", ".txt"],
]);

/** Build a filename that the asset store will accept, from a media type. */
export function filenameFor(mediaType, base = "asset") {
  return `${base}${EXT_BY_TYPE.get(mediaType) ?? ""}`;
}

export class AssetStore {
  #db;
  #root;
  #now;

  /** @param {{ dbPath?: string, root: string, db?: object, now?: () => string }} opts */
  constructor({ dbPath, root, db, now = () => new Date().toISOString() }) {
    this.#db = db ?? openDb(dbPath);
    this.#db.exec(ASSET_SCHEMA);
    this.#root = resolve(root);
    this.#now = now;
    mkdirSync(join(this.#root, "assets"), { recursive: true });
    mkdirSync(join(this.#root, "tmp"), { recursive: true });
    mkdirSync(join(this.#root, "exports"), { recursive: true });
  }

  /**
   * Import bytes as an asset.
   *
   * @param {{ bytes: Uint8Array, displayName: string, mediaType?: string,
   *           origin: string, sourceJobId?: string|null, licenseSource?: string|null }} input
   */
  async put({ bytes, displayName, mediaType, origin, sourceJobId = null, licenseSource = null }) {
    // Sniff the container from the bytes. A client-declared Content-Type is
    // untrusted input: curl sends application/octet-stream for a .wav, and a
    // caller could declare anything at all.
    const sniffed = sniffContainer(bytes);
    const ext = extname(displayName).toLowerCase();
    // A generic content type means "I do not know", not "I claim otherwise",
    // so it is not treated as a contradicting declaration.
    const GENERIC = new Set(["", "application/octet-stream", "binary/octet-stream"]);
    const rawDeclared = mediaType ?? ALLOWED.get(ext) ?? null;
    const declared = rawDeclared && !GENERIC.has(rawDeclared) && ALLOWED.has(ext)
      ? rawDeclared
      : null;
    const type = sniffed ?? declared;

    if (!type) {
      const err = new TypeError(
        `无法识别的素材类型：${displayName}（既不匹配文件头，也不匹配已知扩展名）`,
      );
      err.code = "VALIDATION_ERROR";
      throw err;
    }
    // A declared type that contradicts the bytes is a mismatch worth refusing.
    if (sniffed && declared && sniffed.split(";")[0] !== declared.split(";")[0]) {
      const err = new TypeError(
        `文件内容（${sniffed}）与声明的类型（${declared}）不一致`,
      );
      err.code = "VALIDATION_ERROR";
      throw err;
    }
    if (bytes.byteLength > MAX_ASSET_BYTES) {
      throw new TypeError("asset exceeds the local size limit");
    }

    const hash = hashBytes(bytes);
    const existing = this.#db
      .prepare("SELECT * FROM assets WHERE content_hash = ?")
      .get(hash);
    // Re-importing the same bytes is the "re-download, do not regenerate"
    // path. It resolves to the asset we already have.
    if (existing) {
      return { asset: this.#toPublic(existing), created: false };
    }

    const id = randomUUID();
    // Shard by the server-generated id, never by the filename.
    const dir = join(this.#root, "assets", id.slice(0, 2));
    mkdirSync(dir, { recursive: true });
    const storagePath = join(dir, `${id}${extname(displayName).toLowerCase()}`);

    await this.#atomicWrite(storagePath, bytes);

    this.#db
      .prepare(
        `INSERT INTO assets
           (id, content_hash, byte_size, media_type, storage_path, display_name,
            source_job_id, origin, license_source, created_at)
         VALUES (?,?,?,?,?,?,?,?,?,?)`,
      )
      .run(
        id,
        hash,
        bytes.byteLength,
        type,
        storagePath,
        safeDisplayName(displayName),
        sourceJobId,
        origin,
        licenseSource,
        this.#now(),
      );

    return { asset: this.get(id), created: true };
  }

  get(id) {
    const row = this.#db.prepare("SELECT * FROM assets WHERE id = ?").get(id);
    return row ? this.#toPublic(row) : null;
  }

  list() {
    return this.#db
      .prepare("SELECT * FROM assets ORDER BY created_at DESC")
      .all()
      .map((r) => this.#toPublic(r));
  }

  /** Absolute path, for server-side reads only. Never returned over HTTP. */
  resolvePath(id) {
    const row = this.#db.prepare("SELECT * FROM assets WHERE id = ?").get(id);
    if (!row) return null;
    const p = resolve(row.storage_path);
    // Defence in depth: the stored path must still be inside our root.
    if (p !== this.#root && !p.startsWith(this.#root + "/")) return null;
    return p;
  }

  read(id) {
    const p = this.resolvePath(id);
    if (!p || !existsSync(p)) return null;
    return readFileSync(p);
  }

  /**
   * Delete, but only if nothing references it. Returns the reference list
   * rather than breaking a project silently.
   *
   * @param {string} id
   * @param {{ referencedBy?: string[] }} refs
   */
  remove(id, { referencedBy = [] } = {}) {
    if (referencedBy.length) {
      const err = new Error("asset is still referenced");
      err.code = "REVISION_CONFLICT";
      err.referencedBy = referencedBy;
      throw err;
    }
    const p = this.resolvePath(id);
    const row = this.#db.prepare("SELECT * FROM assets WHERE id = ?").get(id);
    if (!row) return false;
    this.#db.prepare("DELETE FROM assets WHERE id = ?").run(id);
    if (p && existsSync(p)) unlinkSync(p);
    return true;
  }

  /** Bytes on disk, for the storage settings screen. */
  usage() {
    let total = 0;
    let count = 0;
    for (const row of this.#db.prepare("SELECT byte_size FROM assets").all()) {
      total += row.byte_size;
      count += 1;
    }
    return { totalBytes: total, count };
  }

  /** Temp files older than `maxAgeMs`, for the cleanup sweep. */
  sweepTemp(maxAgeMs = 24 * 60 * 60 * 1000) {
    const dir = join(this.#root, "tmp");
    if (!existsSync(dir)) return 0;
    let removed = 0;
    const cutoff = Date.now() - maxAgeMs;
    for (const name of readdirSafe(dir)) {
      const p = join(dir, name);
      try {
        if (statSync(p).mtimeMs < cutoff) {
          unlinkSync(p);
          removed += 1;
        }
      } catch {
        /* skip */
      }
    }
    return removed;
  }

  #toPublic(row) {
    return {
      id: row.id,
      contentHash: row.content_hash,
      byteSize: row.byte_size,
      mediaType: row.media_type,
      // A route, not a path. The filesystem layout is never disclosed.
      url: `/api/v1/assets/${row.id}`,
      displayName: row.display_name,
      sourceJobId: row.source_job_id,
      origin: row.origin,
      licenseSource: row.license_source,
      createdAt: row.created_at,
    };
  }

  /** Write via a temp file + rename so readers never see a partial file. */
  async #atomicWrite(target, bytes) {
    const tmp = join(this.#root, "tmp", `${randomUUID()}.part`);
    try {
      await pipeline(
        (async function* () {
          yield bytes;
        })(),
        createWriteStream(tmp),
      );
      renameSync(tmp, target);
    } catch (err) {
      if (existsSync(tmp)) {
        try {
          unlinkSync(tmp);
        } catch {
          /* ignore */
        }
      }
      if (err?.code === "ENOSPC") throw new StorageFullError("磁盘空间不足");
      throw err;
    }
  }

  close() {
    this.#db.close();
  }
}

/* ------------------------------------------------------------- helpers -- */

function hashBytes(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

function sniffType(name) {
  return ALLOWED.get(extname(name).toLowerCase()) ?? null;
}

/**
 * Read the real container from the file's magic bytes. Returns null when the
 * header is not recognised, so the caller can fall back to the extension.
 */
function sniffContainer(bytes) {
  if (!bytes || bytes.byteLength < 12) return null;
  const tag = (o, n) => String.fromCharCode(...bytes.subarray(o, o + n));
  if (tag(0, 4) === "RIFF" && tag(8, 4) === "WAVE") return "audio/wav";
  if (tag(0, 4) === "fLaC") return "audio/flac";
  if (tag(0, 4) === "OggS") return "audio/ogg";
  if (tag(0, 3) === "ID3") return "audio/mpeg";
  if (bytes[0] === 0xff && (bytes[1] & 0xe0) === 0xe0) return "audio/mpeg";
  if (tag(4, 4) === "ftyp") return "audio/mp4";
  if (bytes[0] === 0x89 && tag(1, 3) === "PNG") return "image/png";
  if (bytes[0] === 0xff && bytes[1] === 0xd8) return "image/jpeg";
  if (tag(0, 4) === "RIFF" && tag(8, 4) === "WEBP") return "image/webp";
  return null;
}

/**
 * A display name is a label, not a path. Strip anything that could be used to
 * reconstruct a location or to escape a directory.
 */
function safeDisplayName(name) {
  return String(name)
    .replace(/[/\\]/g, "_")
    .replace(/^\.+/, "_")
    .replace(/[ -]/g, "")
    .slice(0, 180) || "未命名素材";
}

function readdirSafe(dir) {
  try {
    return readdirSync(dir);
  } catch {
    return [];
  }
}
